// Generated by CoffeeScript 1.3.3
(function() {
  var checkAnswer, count, countDown, nextQuestion, question_count, startGame, typing_timeout;

  typing_timeout = void 0;

  $(function() {
    $("#game").hide();
    $("#gameover").hide();
    $("#answer_text").bind("textchange", function() {
      return checkAnswer();
    });
    $("#play_btn").click(function() {
      return startGame();
    });
    return $("#replay_btn").click(function() {
      return startGame();
    });
  });

  count = void 0;

  question_count = void 0;

  startGame = function() {
    $("#start").hide();
    $("#gameover").hide();
    $("#game").show();
    count = 11;
    countDown();
    $("#answer_text").removeClass("wrong");
    return $("#answer_text").val("");
  };

  countDown = function() {
    var question_timer;
    if (count-- <= 1) {
      console.info("時間切れ");
      $("#game").hide();
      return $("#gameover").show();
    } else {
      $(".timer").text("残り" + count + "秒");
      console.info(count);
      clearTimeout(question_timer);
      return question_timer = setTimeout(function() {
        return countDown();
      }, 1100);
    }
  };

  checkAnswer = function() {
    var self;
    self = this;
    clearTimeout(typing_timeout);
    return typing_timeout = setTimeout(function() {
      var answer;
      answer = $("#answer_text").val();
      console.info(answer);
      if (answer.indexOf("まぼろしのぎんじ") !== -1) {
        console.info("正解");
        return $("#answer_text").removeClass("wrong");
      } else {
        console.info("不正解");
        return $("#answer_text").addClass("wrong");
      }
    }, 500);
  };

  nextQuestion = function() {};

}).call(this);
